import type { Metadata } from "next";
import "./globals.css";
import { Rufina, Oxygen } from "next/font/google";

const rufina = Rufina({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-rufina",
});

const oxygen = Oxygen({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  display: "swap",
  variable: "--font-oxygen",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${rufina.variable} ${oxygen.variable} font-sans`}
      >
        {children}
      </body>
    </html>
  );
}
